### ISSUE TITLE
How to use group collection rules

### ISSUE THREAD

**Issue by wpferguson** [micharambou/darktable-group-view#1]
Here's an example that uses the group collection rules that just got merged today.  You need master to test it, or wait until 4.8.

Feel free to use the bits of code you need or the ideas in your script.

[groupinfo.zip](https://github.com/micharambou/darktable-group-view/files/15102007/groupinfo.zip)

**Comment by micharambou** [comment]
Thanks!

Changes can be found in 4.8-adaption branch and will be merged when DT 4.8 is released.

**Comment by micharambou** [comment]
Merged into master
